/**
 * 全球预设热门路线与区域元数据
 * 作为后端 `/v1/itineraries/regions` 的前端回退数据与首屏展示数据
 */
import type { CommunityRoute, Continent, FeaturedSubRegion, RegionMeta } from './types';

export const PRESET_ROUTES: CommunityRoute[] = [
  {
    id: 'preset-okinawa-24h',
    title: '冲绳 24H 海风快闪，¥1800 暴走版',
    destination: '冲绳',
    continent: 'Asia',
    sub_region: 'EastAsia',
    total_hours: 24,
    budget: { amount: 1800, currency: 'CNY' },
    copy_count: 328,
    tags: ['海岛躺平', '极限吃货'],
    summary: {
      total_hours: 24,
      estimated_total_cost: { amount: 1800, currency: 'CNY' },
    },
    legs: [
      {
        index: 0,
        start_time_local: '2026-03-15T09:00:00',
        end_time_local: '2026-03-15T10:30:00',
        activity_type: 'food',
        place: { name: '泊港渔市场', latitude: 26.2253, longitude: 127.6739 },
        transport: { mode: 'taxi' },
        estimated_cost: { amount: 60, currency: 'CNY' },
        tips: ['早上海鲜饭最新鲜'],
      },
    ],
  },
  {
    id: 'preset-bangkok-24h',
    title: '曼谷 24H 极限吃货路线，¥200 封顶',
    destination: '曼谷',
    continent: 'Asia',
    sub_region: 'SoutheastAsia',
    total_hours: 24,
    budget: { amount: 200, currency: 'CNY' },
    copy_count: 267,
    tags: ['极限吃货', '打卡狂魔'],
    summary: {
      total_hours: 24,
      estimated_total_cost: { amount: 200, currency: 'CNY' },
    },
    legs: [
      {
        index: 0,
        start_time_local: '2026-04-01T07:00:00',
        end_time_local: '2026-04-01T08:00:00',
        activity_type: 'food',
        place: { name: '胜利纪念碑船面', latitude: 13.765, longitude: 100.5388 },
        transport: { mode: 'metro', reference: 'BTS 胜利纪念碑站' },
        estimated_cost: { amount: 8, currency: 'CNY' },
        tips: ['一碗才 40 泰铢'],
      },
    ],
  },
  {
    id: 'preset-london-24h',
    title: '伦敦 24H 王炸打卡，¥2200 快闪版',
    destination: '伦敦',
    continent: 'Europe',
    sub_region: 'UK',
    total_hours: 24,
    budget: { amount: 2200, currency: 'CNY' },
    copy_count: 188,
    tags: ['打卡狂魔', '博物馆'],
    summary: {
      total_hours: 24,
      estimated_total_cost: { amount: 2200, currency: 'CNY' },
    },
    legs: [
      {
        index: 0,
        start_time_local: '2026-07-01T08:00:00',
        end_time_local: '2026-07-01T10:00:00',
        activity_type: 'attraction',
        place: { name: '白金汉宫', latitude: 51.5014, longitude: -0.1419 },
        transport: { mode: 'metro' },
        estimated_cost: { amount: 0, currency: 'CNY' },
        tips: ['换岗仪式看时间'],
      },
    ],
  },
  {
    id: 'preset-paris-48h',
    title: '巴黎 48H 城市光影巡礼，¥3200 经典版',
    destination: '巴黎',
    continent: 'Europe',
    sub_region: 'ContinentalEurope',
    total_hours: 48,
    budget: { amount: 3200, currency: 'CNY' },
    copy_count: 221,
    tags: ['浪漫打卡', '博物馆'],
    summary: {
      total_hours: 48,
      estimated_total_cost: { amount: 3200, currency: 'CNY' },
    },
    legs: [
      {
        index: 0,
        start_time_local: '2026-08-01T09:00:00',
        end_time_local: '2026-08-01T12:00:00',
        activity_type: 'attraction',
        place: { name: '卢浮宫', latitude: 48.8606, longitude: 2.3376 },
        transport: { mode: 'metro' },
        estimated_cost: { amount: 180, currency: 'CNY' },
        tips: ['提前预约省排队'],
      },
    ],
  },
  {
    id: 'preset-rio-48h',
    title: '里约 48H 山海缆车双修，¥3000 进阶版',
    destination: '里约热内卢',
    continent: 'SouthAmerica',
    sub_region: 'LatinAmerica',
    total_hours: 48,
    budget: { amount: 3000, currency: 'CNY' },
    copy_count: 145,
    tags: ['山海全收', '缆车体验'],
    summary: {
      total_hours: 48,
      estimated_total_cost: { amount: 3000, currency: 'CNY' },
    },
    legs: [
      {
        index: 0,
        start_time_local: '2026-09-02T09:00:00',
        end_time_local: '2026-09-02T12:00:00',
        activity_type: 'attraction',
        place: { name: '面包山', latitude: -22.9486, longitude: -43.1566 },
        transport: { mode: 'taxi' },
        estimated_cost: { amount: 220, currency: 'CNY' },
        tips: ['日落推荐'],
      },
    ],
  },
  {
    id: 'preset-cairo-24h',
    title: '开罗 24H 金字塔快闪，¥2000 核心版',
    destination: '开罗',
    continent: 'Africa',
    sub_region: 'NorthAfrica',
    total_hours: 24,
    budget: { amount: 2000, currency: 'CNY' },
    copy_count: 132,
    tags: ['古迹控', '金字塔'],
    summary: {
      total_hours: 24,
      estimated_total_cost: { amount: 2000, currency: 'CNY' },
    },
    legs: [
      {
        index: 0,
        start_time_local: '2026-10-01T08:00:00',
        end_time_local: '2026-10-01T12:00:00',
        activity_type: 'attraction',
        place: { name: '吉萨金字塔', latitude: 29.9792, longitude: 31.1342 },
        transport: { mode: 'taxi' },
        estimated_cost: { amount: 220, currency: 'CNY' },
        tips: ['建议早去避晒'],
      },
    ],
  },
  // ── 以下为同步后端完整预置路线（精简版） ──
  {
    id: 'preset-okinawa-48h',
    title: '48H 怒刷冲绳，人均 ¥2800 极限挑战',
    destination: '冲绳',
    continent: 'Asia',
    sub_region: 'EastAsia',
    total_hours: 48,
    budget: { amount: 2800, currency: 'CNY' },
    copy_count: 328,
    tags: ['疯狂暴走', '极限吃货'],
    summary: { total_hours: 48, estimated_total_cost: { amount: 2800, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-03-15T08:00:00', end_time_local: '2026-03-15T11:00:00', activity_type: 'flight', place: { name: '那霸机场', latitude: 26.1958, longitude: 127.6459 }, transport: { mode: 'flight', reference: '春秋航空 9C6218' }, estimated_cost: { amount: 800, currency: 'CNY' }, tips: ['提前 2 周订票最便宜'] },
    ],
  },
  {
    id: 'preset-tokyo-48h',
    title: '48H 怒刷东京，人均 ¥3500 暴走攻略',
    destination: '东京',
    continent: 'Asia',
    sub_region: 'EastAsia',
    total_hours: 48,
    budget: { amount: 3500, currency: 'CNY' },
    copy_count: 445,
    tags: ['疯狂暴走', '极限吃货'],
    summary: { total_hours: 48, estimated_total_cost: { amount: 3500, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-04-05T09:00:00', end_time_local: '2026-04-05T10:30:00', activity_type: 'food', place: { name: '筑地场外市场', latitude: 35.6654, longitude: 139.7707 }, transport: { mode: 'metro', reference: '日比谷线→筑地站' }, estimated_cost: { amount: 80, currency: 'CNY' }, tips: ['玉子烧和海鲜丼早餐'] },
    ],
  },
  {
    id: 'preset-osaka-72h',
    title: '72H 大阪吃货 + USJ 全开，¥4200 冲刺版',
    destination: '大阪',
    continent: 'Asia',
    sub_region: 'EastAsia',
    total_hours: 72,
    budget: { amount: 4200, currency: 'CNY' },
    copy_count: 356,
    tags: ['极限吃货', '乐园控'],
    summary: { total_hours: 72, estimated_total_cost: { amount: 4200, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-04-10T09:00:00', end_time_local: '2026-04-10T11:00:00', activity_type: 'food', place: { name: '黑门市场', latitude: 34.6620, longitude: 135.5069 }, transport: { mode: 'metro', reference: '日本桥站' }, estimated_cost: { amount: 80, currency: 'CNY' }, tips: ['刺身和和牛串起步'] },
    ],
  },
  {
    id: 'preset-fukuoka-24h',
    title: '福冈 24H 拉面快闪，¥1600 轻装版',
    destination: '福冈',
    continent: 'Asia',
    sub_region: 'EastAsia',
    total_hours: 24,
    budget: { amount: 1600, currency: 'CNY' },
    copy_count: 189,
    tags: ['极限吃货', '城市漫游'],
    summary: { total_hours: 24, estimated_total_cost: { amount: 1600, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-04-18T08:00:00', end_time_local: '2026-04-18T09:00:00', activity_type: 'food', place: { name: '元祖长滨屋', latitude: 33.5956, longitude: 130.3924 }, transport: { mode: 'taxi' }, estimated_cost: { amount: 35, currency: 'CNY' }, tips: ['豚骨拉面开门即吃'] },
    ],
  },
  {
    id: 'preset-sapporo-48h',
    title: '札幌 48H 雪国食堂巡礼，¥2800 进阶版',
    destination: '札幌',
    continent: 'Asia',
    sub_region: 'EastAsia',
    total_hours: 48,
    budget: { amount: 2800, currency: 'CNY' },
    copy_count: 203,
    tags: ['极限吃货', '雪国体验'],
    summary: { total_hours: 48, estimated_total_cost: { amount: 2800, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-02-06T09:00:00', end_time_local: '2026-02-06T11:00:00', activity_type: 'food', place: { name: '二条市场', latitude: 43.0585, longitude: 141.3599 }, transport: { mode: 'metro', reference: '大通站' }, estimated_cost: { amount: 90, currency: 'CNY' }, tips: ['海鲜盖饭必吃'] },
    ],
  },
  {
    id: 'preset-seoul-48h',
    title: '48H 首尔暴走，¥2000 韩流朝圣',
    destination: '首尔',
    continent: 'Asia',
    sub_region: 'EastAsia',
    total_hours: 48,
    budget: { amount: 2000, currency: 'CNY' },
    copy_count: 312,
    tags: ['疯狂暴走', '打卡狂魔'],
    summary: { total_hours: 48, estimated_total_cost: { amount: 2000, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-05-01T09:00:00', end_time_local: '2026-05-01T11:00:00', activity_type: 'attraction', place: { name: '景福宫', latitude: 37.5796, longitude: 126.9770 }, transport: { mode: 'metro', reference: '3号线景福宫站' }, estimated_cost: { amount: 15, currency: 'CNY' }, tips: ['韩服可免票'] },
    ],
  },
  {
    id: 'preset-taipei-72h',
    title: '台北 72H 夜市 + 山城全吃透，¥2200 深度版',
    destination: '台北',
    continent: 'Asia',
    sub_region: 'EastAsia',
    total_hours: 72,
    budget: { amount: 2200, currency: 'CNY' },
    copy_count: 298,
    tags: ['夜市王者', '山城打卡'],
    summary: { total_hours: 72, estimated_total_cost: { amount: 2200, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-05-25T08:00:00', end_time_local: '2026-05-25T09:30:00', activity_type: 'food', place: { name: '永和豆浆大王', latitude: 25.0330, longitude: 121.5654 }, transport: { mode: 'metro', reference: '东门站' }, estimated_cost: { amount: 10, currency: 'CNY' }, tips: ['烧饼油条起手'] },
    ],
  },
  {
    id: 'preset-chiangmai-48h',
    title: '48H 清迈慢生活，¥400 佛系穷游',
    destination: '清迈',
    continent: 'Asia',
    sub_region: 'SoutheastAsia',
    total_hours: 48,
    budget: { amount: 400, currency: 'CNY' },
    copy_count: 203,
    tags: ['穷游慢生活', '寺庙巡礼'],
    summary: { total_hours: 48, estimated_total_cost: { amount: 400, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-04-20T08:00:00', end_time_local: '2026-04-20T09:30:00', activity_type: 'food', place: { name: '凤飞飞猪脚饭', latitude: 18.7953, longitude: 98.9845 }, transport: { mode: 'taxi' }, estimated_cost: { amount: 8, currency: 'CNY' }, tips: ['北门招牌小吃'] },
    ],
  },
  {
    id: 'preset-singapore-72h',
    title: '新加坡 72H 城市花园全景，¥2200 舒适版',
    destination: '新加坡',
    continent: 'Asia',
    sub_region: 'SoutheastAsia',
    total_hours: 72,
    budget: { amount: 2200, currency: 'CNY' },
    copy_count: 278,
    tags: ['城市打卡', '家庭友好'],
    summary: { total_hours: 72, estimated_total_cost: { amount: 2200, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-04-15T09:00:00', end_time_local: '2026-04-15T11:00:00', activity_type: 'attraction', place: { name: '滨海湾花园', latitude: 1.2816, longitude: 103.8636 }, transport: { mode: 'metro', reference: 'Bayfront站' }, estimated_cost: { amount: 60, currency: 'CNY' }, tips: ['Cloud Forest值得买票'] },
    ],
  },
  {
    id: 'preset-phuket-72h',
    title: '普吉岛 72H 海岛治愈，¥1800 浮潜版',
    destination: '普吉岛',
    continent: 'Asia',
    sub_region: 'SoutheastAsia',
    total_hours: 72,
    budget: { amount: 1800, currency: 'CNY' },
    copy_count: 167,
    tags: ['海岛躺平', '潜水体验'],
    summary: { total_hours: 72, estimated_total_cost: { amount: 1800, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-06-12T10:00:00', end_time_local: '2026-06-12T13:00:00', activity_type: 'attraction', place: { name: '卡伦海滩', latitude: 7.8467, longitude: 98.2946 }, transport: { mode: 'taxi' }, estimated_cost: { amount: 0, currency: 'CNY' }, tips: ['上午人少更适合玩水'] },
    ],
  },
  {
    id: 'preset-penang-24h',
    title: '槟城 24H 壁画 + 小吃暴走，¥500 精华版',
    destination: '槟城',
    continent: 'Asia',
    sub_region: 'SoutheastAsia',
    total_hours: 24,
    budget: { amount: 500, currency: 'CNY' },
    copy_count: 145,
    tags: ['街头美食', '古城打卡'],
    summary: { total_hours: 24, estimated_total_cost: { amount: 500, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-06-20T08:00:00', end_time_local: '2026-06-20T09:30:00', activity_type: 'food', place: { name: '多春茶室', latitude: 5.4185, longitude: 100.3380 }, transport: { mode: 'walk' }, estimated_cost: { amount: 20, currency: 'CNY' }, tips: ['炭烤吐司早餐'] },
    ],
  },
  {
    id: 'preset-bali-72h',
    title: '72H 巴厘岛海岛穷游，¥1200 神仙体验',
    destination: '巴厘岛',
    continent: 'Asia',
    sub_region: 'SoutheastAsia',
    total_hours: 72,
    budget: { amount: 1200, currency: 'CNY' },
    copy_count: 234,
    tags: ['打卡狂魔', '疯狂暴走'],
    summary: { total_hours: 72, estimated_total_cost: { amount: 1200, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-05-10T10:00:00', end_time_local: '2026-05-10T12:00:00', activity_type: 'attraction', place: { name: '海神庙', latitude: -8.6212, longitude: 115.0868 }, transport: { mode: 'taxi' }, estimated_cost: { amount: 20, currency: 'CNY' }, tips: ['日落超值'] },
    ],
  },
  {
    id: 'preset-hcmc-48h',
    title: '48H 怒刷胡志明市，人均 ¥350 挑战',
    destination: '胡志明市',
    continent: 'Asia',
    sub_region: 'SoutheastAsia',
    total_hours: 48,
    budget: { amount: 350, currency: 'CNY' },
    copy_count: 512,
    tags: ['穷鬼免税店', '极限吃货'],
    summary: { total_hours: 48, estimated_total_cost: { amount: 350, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-03-20T08:30:00', end_time_local: '2026-03-20T09:30:00', activity_type: 'food', place: { name: 'Phở Hòa Pasteur', latitude: 10.7769, longitude: 106.6896 }, transport: { mode: 'bus', reference: '109路公交' }, estimated_cost: { amount: 15, currency: 'CNY' }, tips: ['当地人常去牛肉粉'] },
    ],
  },
  {
    id: 'preset-london-48h',
    title: '伦敦 48H 城市经典全收，¥3200 深挖版',
    destination: '伦敦',
    continent: 'Europe',
    sub_region: 'UK',
    total_hours: 48,
    budget: { amount: 3200, currency: 'CNY' },
    copy_count: 188,
    tags: ['城市暴走', '经典必刷'],
    summary: { total_hours: 48, estimated_total_cost: { amount: 3200, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-07-02T09:00:00', end_time_local: '2026-07-02T11:00:00', activity_type: 'attraction', place: { name: '西敏寺 + 国会大厦', latitude: 51.4993, longitude: -0.1273 }, transport: { mode: 'metro', reference: 'Westminster' }, estimated_cost: { amount: 180, currency: 'CNY' }, tips: ['建筑细节非常震撼'] },
    ],
  },
  {
    id: 'preset-edinburgh-72h',
    title: '爱丁堡 72H 中世纪山城，¥2800 沉浸版',
    destination: '爱丁堡',
    continent: 'Europe',
    sub_region: 'UK',
    total_hours: 72,
    budget: { amount: 2800, currency: 'CNY' },
    copy_count: 145,
    tags: ['古堡巡礼', '电影感'],
    summary: { total_hours: 72, estimated_total_cost: { amount: 2800, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-07-10T09:00:00', end_time_local: '2026-07-10T12:00:00', activity_type: 'attraction', place: { name: '爱丁堡城堡', latitude: 55.9486, longitude: -3.1999 }, transport: { mode: 'walk' }, estimated_cost: { amount: 180, currency: 'CNY' }, tips: ['山顶视野非常值'] },
    ],
  },
  {
    id: 'preset-rome-72h',
    title: '罗马 72H 古城穿越，¥2800 深度版',
    destination: '罗马',
    continent: 'Europe',
    sub_region: 'ContinentalEurope',
    total_hours: 72,
    budget: { amount: 2800, currency: 'CNY' },
    copy_count: 156,
    tags: ['古迹控', '徒步线'],
    summary: { total_hours: 72, estimated_total_cost: { amount: 2800, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-08-10T09:00:00', end_time_local: '2026-08-10T12:00:00', activity_type: 'attraction', place: { name: '斗兽场', latitude: 41.8902, longitude: 12.4922 }, transport: { mode: 'metro', reference: 'Colosseo' }, estimated_cost: { amount: 160, currency: 'CNY' }, tips: ['热门景点提前预约'] },
    ],
  },
  {
    id: 'preset-barcelona-24h',
    title: '巴塞罗那 24H 高迪暴走，¥1800 精华版',
    destination: '巴塞罗那',
    continent: 'Europe',
    sub_region: 'ContinentalEurope',
    total_hours: 24,
    budget: { amount: 1800, currency: 'CNY' },
    copy_count: 134,
    tags: ['建筑巡礼', '地中海'],
    summary: { total_hours: 24, estimated_total_cost: { amount: 1800, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-08-15T08:30:00', end_time_local: '2026-08-15T10:30:00', activity_type: 'attraction', place: { name: '圣家堂', latitude: 41.4036, longitude: 2.1744 }, transport: { mode: 'metro', reference: 'Sagrada Familia' }, estimated_cost: { amount: 210, currency: 'CNY' }, tips: ['建议预约早场'] },
    ],
  },
  {
    id: 'preset-amsterdam-48h',
    title: '阿姆斯特丹 48H 运河慢游，¥2600 轻松版',
    destination: '阿姆斯特丹',
    continent: 'Europe',
    sub_region: 'ContinentalEurope',
    total_hours: 48,
    budget: { amount: 2600, currency: 'CNY' },
    copy_count: 156,
    tags: ['运河城市', '博物馆'],
    summary: { total_hours: 48, estimated_total_cost: { amount: 2600, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-08-20T09:00:00', end_time_local: '2026-08-20T12:00:00', activity_type: 'attraction', place: { name: '梵高博物馆', latitude: 52.3584, longitude: 4.8811 }, transport: { mode: 'bus' }, estimated_cost: { amount: 160, currency: 'CNY' }, tips: ['预约是关键'] },
    ],
  },
  {
    id: 'preset-rio-24h',
    title: '里约 24H 山海快闪，¥2200 精华版',
    destination: '里约热内卢',
    continent: 'SouthAmerica',
    sub_region: 'LatinAmerica',
    total_hours: 24,
    budget: { amount: 2200, currency: 'CNY' },
    copy_count: 123,
    tags: ['海滩打卡', '城市景观'],
    summary: { total_hours: 24, estimated_total_cost: { amount: 2200, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-09-01T08:00:00', end_time_local: '2026-09-01T10:00:00', activity_type: 'attraction', place: { name: '基督像', latitude: -22.9519, longitude: -43.2105 }, transport: { mode: 'taxi' }, estimated_cost: { amount: 180, currency: 'CNY' }, tips: ['清晨云层更稳'] },
    ],
  },
  {
    id: 'preset-newyork-48h',
    title: '纽约 48H 摩天楼暴走，¥4200 经典版',
    destination: '纽约',
    continent: 'NorthAmerica',
    sub_region: 'NorthAmericaCore',
    total_hours: 48,
    budget: { amount: 4200, currency: 'CNY' },
    copy_count: 167,
    tags: ['城市暴走', '地标打卡'],
    summary: { total_hours: 48, estimated_total_cost: { amount: 4200, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-11-01T09:00:00', end_time_local: '2026-11-01T11:00:00', activity_type: 'attraction', place: { name: '中央公园', latitude: 40.7829, longitude: -73.9654 }, transport: { mode: 'metro' }, estimated_cost: { amount: 0, currency: 'CNY' }, tips: ['早晨慢走舒服'] },
    ],
  },
  {
    id: 'preset-sydney-48h',
    title: '悉尼 48H 海港经典，¥3600 轻奢版',
    destination: '悉尼',
    continent: 'Oceania',
    sub_region: 'OceaniaCore',
    total_hours: 48,
    budget: { amount: 3600, currency: 'CNY' },
    copy_count: 145,
    tags: ['海港城市', '地标打卡'],
    summary: { total_hours: 48, estimated_total_cost: { amount: 3600, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-12-01T09:00:00', end_time_local: '2026-12-01T11:00:00', activity_type: 'attraction', place: { name: '悉尼歌剧院', latitude: -33.8568, longitude: 151.2153 }, transport: { mode: 'train', reference: 'Circular Quay' }, estimated_cost: { amount: 220, currency: 'CNY' }, tips: ['可加导览'] },
    ],
  },
  {
    id: 'preset-melbourne-24h',
    title: '墨尔本 24H 咖啡巷弄快闪，¥2200 轻文艺版',
    destination: '墨尔本',
    continent: 'Oceania',
    sub_region: 'OceaniaCore',
    total_hours: 24,
    budget: { amount: 2200, currency: 'CNY' },
    copy_count: 134,
    tags: ['咖啡城市', '巷弄文化'],
    summary: { total_hours: 24, estimated_total_cost: { amount: 2200, currency: 'CNY' } },
    legs: [
      { index: 0, start_time_local: '2026-12-05T08:30:00', end_time_local: '2026-12-05T10:00:00', activity_type: 'food', place: { name: 'Degraves Street', latitude: -37.8179, longitude: 144.9667 }, transport: { mode: 'walk' }, estimated_cost: { amount: 80, currency: 'CNY' }, tips: ['咖啡馆集中'] },
    ],
  },
];

export const TRAVEL_TAGS = [
  { key: '疯狂暴走', emoji: '🏃' },
  { key: '极限吃货', emoji: '🍜' },
  { key: '穷鬼免税店', emoji: '🛍️' },
  { key: '打卡狂魔', emoji: '📸' },
] as const;

export const CONTINENT_OPTIONS: Array<{ key: Continent; label: string }> = [
  { key: 'Asia', label: '亚洲' },
  { key: 'Europe', label: '欧洲' },
  { key: 'Africa', label: '非洲' },
  { key: 'NorthAmerica', label: '北美' },
  { key: 'SouthAmerica', label: '南美' },
  { key: 'Oceania', label: '大洋洲' },
] as const;

export const FEATURED_SUB_REGIONS_FALLBACK: FeaturedSubRegion[] = [
  { key: 'EastAsia', label: '东亚', preset_count: 6, hot_destinations: ['冲绳', '东京', '大阪', '首尔', '台北', '福冈'] },
  { key: 'SoutheastAsia', label: '东南亚', preset_count: 7, hot_destinations: ['曼谷', '清迈', '新加坡', '普吉岛', '槟城', '巴厘岛'] },
  { key: 'ContinentalEurope', label: '欧洲大陆', preset_count: 4, hot_destinations: ['巴黎', '罗马', '巴塞罗那', '阿姆斯特丹'] },
  { key: 'UK', label: '英国', preset_count: 5, hot_destinations: ['伦敦', '爱丁堡', '曼彻斯特', '利物浦'] },
  { key: 'LatinAmerica', label: '拉丁美洲', preset_count: 6, hot_destinations: ['里约热内卢', '圣保罗', '布宜诺斯艾利斯', '利马', '圣地亚哥'] },
  { key: 'NorthAfrica', label: '北非', preset_count: 3, hot_destinations: ['开罗', '马拉喀什'] },
  { key: 'SubSaharanAfrica', label: '撒哈拉以南非洲', preset_count: 3, hot_destinations: ['开普敦', '内罗毕', '桑给巴尔'] },
];

export const REGION_METADATA_FALLBACK: RegionMeta[] = [
  {
    key: 'Asia',
    label: '亚洲',
    preset_count: 13,
    hot_destinations: ['冲绳', '东京', '大阪', '首尔', '台北', '曼谷', '清迈', '新加坡', '普吉岛', '槟城', '巴厘岛', '胡志明市'],
    sub_regions: [
      { key: 'EastAsia', label: '东亚', preset_count: 6 },
      { key: 'SoutheastAsia', label: '东南亚', preset_count: 7 },
    ],
  },
  {
    key: 'Europe',
    label: '欧洲',
    preset_count: 9,
    hot_destinations: ['伦敦', '爱丁堡', '曼彻斯特', '利物浦', '巴黎', '罗马', '巴塞罗那', '阿姆斯特丹'],
    sub_regions: [
      { key: 'UK', label: '英国', preset_count: 5 },
      { key: 'ContinentalEurope', label: '欧洲大陆', preset_count: 4 },
    ],
  },
  {
    key: 'Africa',
    label: '非洲',
    preset_count: 6,
    hot_destinations: ['开罗', '马拉喀什', '开普敦', '内罗毕', '桑给巴尔'],
    sub_regions: [
      { key: 'NorthAfrica', label: '北非', preset_count: 3 },
      { key: 'SubSaharanAfrica', label: '撒哈拉以南非洲', preset_count: 3 },
    ],
  },
  {
    key: 'NorthAmerica',
    label: '北美',
    preset_count: 2,
    hot_destinations: ['纽约', '洛杉矶'],
    sub_regions: [{ key: 'NorthAmericaCore', label: '北美核心', preset_count: 2 }],
  },
  {
    key: 'SouthAmerica',
    label: '南美',
    preset_count: 6,
    hot_destinations: ['里约热内卢', '圣保罗', '布宜诺斯艾利斯', '利马', '圣地亚哥'],
    sub_regions: [{ key: 'LatinAmerica', label: '拉丁美洲', preset_count: 6 }],
  },
  {
    key: 'Oceania',
    label: '大洋洲',
    preset_count: 2,
    hot_destinations: ['悉尼', '墨尔本'],
    sub_regions: [{ key: 'OceaniaCore', label: '大洋洲', preset_count: 2 }],
  },
];

export const HOT_DESTINATIONS = PRESET_ROUTES.map(route => route.destination) as string[];
